import itertools


class Registry:
    """
    The central registry for all entities in the galaxy.
    This acts as the 'Source of Truth' for the simulation.
    Should only have register and 'get' methods.
    """

    def __init__(self):
        # 1. THE ID GENERATOR
        # This ensures every single thing in your galaxy has a unique 'Social Security Number'
        self._id_gen = itertools.count(start=1000)

        # 2. THE REGISTRIES (The 'Tables' of your database)
        # We use dictionaries {id: object} for O(1) lookup speed
        self.nations = {}
        self.solar_systems = {}
        self.celestial_bodies = {}
        self.colonies = {}
        self.buildings = {}
        self.jobs = {}
        self.pops = {}
        self.ships = {}

        # 3. THE MANAGERS (The 'Ministries' that handle logic)
        # You will create these classes later to keep the Universe class slim
        # self.economy_manager = EconomyManager()
        # self.labor_manager = LaborManager()
        # self.population_manager = PopulationManager()
        # self.military_manager = MilitaryManager()

    def get_uid(self):
        """Generates a new, unique integer ID."""
        return next(self._id_gen)

    # --- REGISTRATION METHODS ---
    # These methods take a fresh object, give it an ID, and file it away.

    # The arguments go: object itself, and IDs pointing to any relationships it has. 

    def register_galaxy(self, galaxy):
        uid = self.get_uid()
        galaxy.uid = uid
        galaxy.registry = self
        self.galaxy = galaxy  # Assuming there's only one galaxy, we can store it directly.
        return uid

    def register_nation(self, nation):
        uid = self.get_uid()
        nation.uid = uid
        nation.registry = self
        self.nations[uid] = nation
        return uid

    def register_colony(self, colony, planet_id, owner_id):
        uid = self.get_uid()
        colony.uid = uid
        colony.registry = self
        colony.planet_id = planet_id
        colony.owner_id = owner_id
        self.colonies[uid] = colony
        return uid

    def register_building(self, building, colony_id):
        uid = self.get_uid()
        building.uid = uid
        building.registry = self
        building.colony_id = colony_id
        self.buildings[uid] = building

        # Automatically register the jobs inside this building
        if hasattr(building, 'jobs'):
            for job in building.jobs:
                self.register_job(job, building.uid, colony_id)
        return uid

    def register_job(self, job, building_id, colony_id):
        uid = self.get_uid()
        job.uid = uid
        job.registry = self
        job.building_id = building_id
        job.colony_id = colony_id
        self.jobs[uid] = job
        return uid

    def register_pop(self, pop, colony_id, job_id=None):
        uid = self.get_uid()
        pop.uid = uid
        pop.registry = self
        pop.colony_id = colony_id
        pop.job_id = job_id
        self.pops[uid] = pop
        return uid

    # --- Registration for World Entities ---

    def register_solar_system(self, solar_system):
        uid = self.get_uid()
        solar_system.uid = uid
        solar_system.registry = self
        self.solar_systems[uid] = solar_system
        return uid

    def register_celestial_body(self, celestial_body):
        uid = self.get_uid()
        celestial_body.uid = uid
        celestial_body.registry = self
        #celestial_body.solar_system_id = solar_system_id
        #celestial_body.parent_id = parent_id
        self.celestial_bodies[uid] = celestial_body
        return uid

    # --- QUERY METHODS ---
    # These replace your nested for-loops.
    def get_anything(self, category, object_uid):
        # This fetches the dictionary (e.g., self.ships) based on the string 'category'
        registry_dict = getattr(self, category)

        # Then you can access the UID within that dictionary
        target = registry_dict.get(f"{object_uid}")
        return target

    def get_celestials_within_starsystem(self, solar_system_id):
        """Returns a list of all celestial bodies within a given solar system."""
        return [b for b in self.celestial_bodies.values() if b.solar_system_id == solar_system_id]

    def get_pops_on_colony(self, colony_id):
        """Returns a list of all Pop objects residing on a specific colony."""
        return [p for p in self.pops.values() if p.colony_id == colony_id]

    def get_unemployed_on_colony(self, colony_id):
        """Social Science query: Find labor surplus for a specific colony."""
        return [p for p in self.pops.values() if p.colony_id == colony_id and p.job_id is None]

    def get_nation_gdp(self, nation_id):
        """Calculate total wealth generated by all colonies in a nation."""
        relevant_colonies = [c.uid for c in self.colonies.values() if c.owner_id == nation_id]
        # You can now sum up production from buildings linked to these colony IDs
        pass


"""Tips and tricks of the universe pattern: - The Universe class is your 'Source of Truth' for all entities. It 
should be the only place where objects are created and stored.

for storing relationships:
for many to one or one to many relationships, source of truth is the child which holds the UID of its owner/parent.
Said object's owner/parent then stores the relationship as a lookup property.
For a many to many relationship, simply create a parent/owner that can track relationships as a sort of membership list.
Think of the game itself that you're cloning for examples: Federations, Galactic Community, join Customs Union, etc.

"""
class Registry:
    def __init__(self):
        self.colonies = {}
        # This is our 'Subscriber List'
        self._subscribers = []

    def subscribe(self, callback_function):
        """Allows other systems to sign up for notifications."""
        self._subscribers.append(callback_function)

    def emit(self, event_name, data):
        """Sends the message to everyone on the list."""
        for callback in self._subscribers:
            callback(event_name, data)

# --- THE SUBSCRIBERS (The Listeners) ---

def update_ui_colors(event_name, data):
    if event_name == "COLONY_FLIP":
        print(f"UI: Changing map color for {data['name']}!")

def recalculate_taxes(event_name, data):
    if event_name == "COLONY_FLIP":
        print(f"ECON: Moving tax revenue from {data['old']} to {data['new']}.")

# --- SETTING IT UP ---

reg = Registry()
# These systems 'sign up' once at the start of the game
reg.subscribe(update_ui_colors)
reg.subscribe(recalculate_taxes)

# --- THE ACTION ---

# When the owner changes, you just do ONE thing:
reg.emit("COLONY_FLIP", {"name": "Alpha Centauri", "old": "Earth", "new": "Mars"})


class Architect:
    def __init__(self):
        # 1. Initialize the Hubs (The Data)
        self.registry = Registry()
        self.calendar = Calendar(self)  # From your uploaded file

        # 2. Initialize the Spokes (The Logic)
        self.relationships = RelationshipManager(self.registry)
        self.economy = EconomyManager(self.registry)

        # 3. THE WIRING: This is where functions move across classes
        # We tell the Registry: "When an event happens, run the Economy Manager's logic"
        self.registry.subscribe(self.economy.handle_event)

        # We can even link your Calendar to the Registry
        # "Every day, tell the registry to emit a 'NEW_DAY' event"
        self.calendar.add_daily_observer(self.registry_daily_bridge)

    def registry_daily_bridge(self):
        """A small helper to push Calendar ticks into the Event System"""
        self.registry.emit("TICK_DAY", {"date": self.calendar.current_date})