import itertools

class Universe:
    """
    The central registry for all entities in the galaxy.
    This acts as the 'Source of Truth' for the simulation.
    """
    def __init__(self):
        # 1. THE ID GENERATOR
        # This ensures every single thing in your galaxy has a unique 'Social Security Number'
        self._id_gen = itertools.count(start=1000)

        # 2. THE REGISTRIES (The 'Tables' of your database)
        # We use dictionaries {id: object} for O(1) lookup speed
        self.nations = {}
        self.solar_systems = {}
        self.planets = {} # Includes all types of celestial bodies, not just planets.
        self.colonies = {}
        self.buildings = {}
        self.jobs = {}
        self.pops = {}
        self.ships = {}

        # 3. THE MANAGERS (The 'Ministries' that handle logic)
        # You will create these classes later to keep the Universe class slim
        # self.economy_manager = EconomyManager()
        # self.labor_manager = LaborManager()
        # self.population_manager = PopulationManager()
        # self.military_manager = MilitaryManager()

    def get_uid(self):
        """Generates a new, unique integer ID."""
        return next(self._id_gen)

    # --- REGISTRATION METHODS ---
    # These methods take a fresh object, give it an ID, and file it away.

    # The arguments go: object itself, and IDs pointing to any relationships it has. 

    def register_colony(self, colony, planet_id, owner_id):
        uid = self.get_uid()
        colony.uid = uid
        colony.planet_id = planet_id
        colony.owner_id = owner_id
        self.colonies[uid] = colony
        return uid

    def register_building(self, building, colony_id):
        uid = self.get_uid()
        building.uid = uid
        building.colony_id = colony_id
        self.buildings[uid] = building
        
        # Automatically register the jobs inside this building
        if hasattr(building, 'jobs'):
            for job in building.jobs:
                self.register_job(job, building.uid, colony_id)
        return uid

    def register_job(self, job, building_id, colony_id):
        uid = self.get_uid()
        job.uid = uid
        job.building_id = building_id
        job.colony_id = colony_id
        self.jobs[uid] = job
        return uid

    def register_pop(self, pop, colony_id, job_id=None):
        uid = self.get_uid()
        pop.uid = uid
        pop.colony_id = colony_id
        pop.job_id = job_id
        self.pops[uid] = pop
        return uid
    
    # --- Registration for World Entities ---
    
    def register_solar_system(self, solar_system):
        uid = self.get_uid()
        solar_system.uid = uid
        self.solar_systems[uid] = solar_system
        return uid
    
    def register_celestial_body(self, body, solar_system_id, parent_id):
        uid = self.get_uid()
        body.uid = uid
        body.solar_system_id = solar_system_id
        body.parent_id = parent_id
        self.planets[uid] = body
        return uid

    # --- QUERY METHODS ---
    # These replace your nested for-loops.

    def get_pops_on_colony(self, colony_id):
        """Returns a list of all Pop objects residing on a specific colony."""
        return [p for p in self.pops.values() if p.colony_id == colony_id]

    def get_unemployed_on_colony(self, colony_id):
        """Social Science query: Find labor surplus for a specific colony."""
        return [p for p in self.pops.values() if p.colony_id == colony_id and p.job_id is None]

    def get_nation_gdp(self, nation_id):
        """Calculate total wealth generated by all colonies in a nation."""
        relevant_colonies = [c.uid for c in self.colonies.values() if c.owner_id == nation_id]
        # You can now sum up production from buildings linked to these colony IDs
        pass

    # --- Specific Queries for World Entities ---

    def get_planet(self, planet_id):
        """Returns the Planet object for a given planet_id."""
        return self.planets.get(planet_id)
    
    def get_solar_system(self, solar_system_id):
        """Returns the SolarSystem object for a given solar_system_id."""
        return self.solar_systems.get(solar_system_id)
    
    def get_colony(self, colony_id):
        """Returns the Colony object for a given colony_id."""
        return self.colonies.get(colony_id)
    
    def get_nation(self, nation_id):
        """Returns the Nation object for a given nation_id."""
        return self.nations.get(nation_id)

universe = Universe()